#!/usr/bin/env python2.7
import cv2
import numpy as np

vid = VideoCapture(0)



class path:
    startPoint = (0,0)
    endPoint = (0,0)
    length = 0.0
    angle = 0



def findT():
    #_, frame = vid.read()
    frame = cv2.imread("T.jpg")

    # Convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    lower_red = np.array([211, 6, 9])
    upper_blue = np.array([224, 8, 12])
    mask = cv2.inRange(hsv, lower_blue, upper_blue)
    cv2.imshow("image", mask)


def rotateT (image):
    #This function calculates the angle between the thresholded T and the control T.
    return

def findHypotenuse(robPos, targetPos):
    #This function calculates the shortest distance between the target and the robot.
    return

def convertToInstruction(hypotenuse, angle):
    data = {'instruction': 'MOVE', 'value': '500'}
    return data

def main():
    findT()
